import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import IPhoneViewer from "./components/IPhoneViewer";
import BottomNav from "@/app/components/BottomNav";
import {
    LayoutDashboard,
    BookOpenCheck,
    MessageSquareText,
    ClipboardList,
    MoreHorizontal, Navigation,
} from "lucide-react";
import HeaderBar from "@/app/components/HeaderBar";
import MainFrame from "@/app/components/MainFrame";
import OverlayWrapper from "@/app/components/OverlayWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const bottomNavItems = [
    {icon: LayoutDashboard, text: "dashboard", size: "0.6em" , link:"/dashboard"},
    {icon: BookOpenCheck, text: "Log Food", size: "0.6em" , link:"/foodlog"},
    {icon: MessageSquareText, text: "Newsfeed", size: "0.6em", link:"/newsfeed"},
    {icon: ClipboardList, text: "Plans", size: "0.6em", link:"/plans"},
    {icon: MoreHorizontal, text: "More", size: "0.6em", link: "/more"},
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <IPhoneViewer>
            <HeaderBar className={"mt-[20px]"}/>
            <MainFrame>
                {children}
            </MainFrame>
            <div className="bg-blue-600 rounded-t-[30px] pt-6 pb-4">
                <OverlayWrapper/>
            </div>
            <BottomNav items={bottomNavItems}/>
        </IPhoneViewer>

        </body>
        </html>
    );
}
